### ISSUE TITLE
Readme on how to use the plugin would be very helpful

### ISSUE THREAD

**Issue by kavink** [nebula-plugins/gradle-scm-plugin#3]
Gradle dependency lock plugin depends on this plugin but not sure how to use this plugin.

**Comment by bmuschko** [comment]
The documentation of this plugin could certainly be improved. It's work in progress. If you are using the Gradle dependency lock plugin, you don't actually need to know about the functionality if this plugin. It's only used for internal purposes.

**Comment by jmcgarr** [comment]
Closing out. Don't see this issue being prioritized in the near term, since this is an internal plugin and shouldn't be directly used.
