### ISSUE TITLE
Version not uploaded to maven-central

### ISSUE THREAD

**Issue by Cinderhaze** [nebula-plugins/gradle-scm-plugin#5]
The newest version of gradle-scm-plugin in maven central is 2.2.0, updated 30-Jan-2015

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.netflix.nebula%22%20AND%20a%3A%22gradle-scm-plugin%22

I see that there was an attempt for version 3.0.1 https://github.com/nebula-plugins/gradle-scm-plugin/releases/tag/v3.0.1 but it mentions 

> No code changes - releasing again because prior Maven Central sync failed.
That was in october 2015... Is it possible to try releasing to maven central again, or is there a manual process that can be done?

**Comment by rud** [comment]
This is probably an outdated issue now.

**Comment by Cinderhaze** [comment]
Looks like version 5.0.2 is the most current version, updated to central, along with the version in question at the time I wrote the original issue (3.0.1) are in maven central.  Thanks!
